name: Artifacts
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        arch: [x86_64]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - arch: aarch64
            os: ubuntu-latest
          - arch: aarch64
            os: macos-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0-dev.3027+0e26c6149
      - run: |
          zig build test -Dfetch -Dci_target=${{matrix.os}}-${{matrix.arch}}
      - run: |
          zig build -Dfetch -Dci_target=ubuntu-latest-x86_64 -p zig-out-ubuntu-x86_64
      - run: |
          zig build -Dfetch -Dci_target=ubuntu-latest-aarch64 -p zig-out-ubuntu-aarch64
      - run: |
          zig build -Dfetch -Dci_target=macos-latest-x86_64 -p zig-out-macos-x86_64
      - run: |
          zig build -Dfetch -Dci_target=macos-latest-aarch64 -p zig-out-macos-aarch64
      - run: |
          zig build -Dfetch -Dci_target=windows-latest-x86_64 -p zig-out-windows-x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: zigup ${{ matrix.os }}-${{ matrix.arch }}
          path: zig-out/bin/*
