name: Artifacts
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.927+eb5e4ac49
      - run: |
          zig build test -Dfetch -Diguana -Dcpu=baseline
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: zigup ${{ matrix.os }}
          path: zig-out/bin/*
